language: node_js
node_js:
  - "8.1.3"
install:
  - npm install
# before_script:
#   - npm install -g firebase-tools
script:
  - echo "skipping tests"
after_success:
  - npm run lh -- --perf=80 --pwa=80 --a11y=80 --bp=80 --seo=80 https://fabriciofmsilva.com.br
