pygments: true

permalink: /:title/

name: Fabrício Silva
description: My web site poered by Jekyll and GiHub Pages
url: http://www.fabriciofmsilva.com.br
domain: fabriciofmsilva.com.br
twitter: fabriciofmsilva
analytics: UA-22890269-1