pygments: true

permalink: /:title/

name: Fabrício Silva
description: My web site poered by Jekyll and GiHub Pages
url: http://www.fabriciofmsilva.com.br
domain: fabriciofmsilva.com.br
twitter: fabriciofmsilva
plus: https://plus.google.com/105011365395783776506/
analytics: UA-22890269-1