permalink: /:title/

title: Fabrício Silva
name: Fabrício Silva
description: My web site powered by Jekyll and GiHub Pages
domain: fabriciofmsilva.com.br

author: Fabrício Silva
github: http://github.com/fabriciofmsilva
twitter: http://twitter.com/fabriciofmsilva
plus: https://plus.google.com/105011365395783776506/
feedburner: http://feeds.feedburner.com/fabriciofmsilva
analytics: UA-22890269-1

pygments: false

markdown: kramdown
